language: java
# We use the deprecated travis environment "precise", because Gateleen does not yet support the newer redis version of the "trusty" environment.
dist: precise
jdk:
  - oraclejdk8
services:
  - redis-server
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
#  Because newer versions of Chrome are not supported for the deprecated "precise" environment of travis we are using,
#  we download and install an older version of Chrome (v. 48), along with some dependencies.
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget http://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
  - sudo dpkg -i download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
#  We also download the newest version of Chrome Driver that still supports our old version of Chrome (v. 48).
  - wget https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d gateleen-test/src/test/resources/
install:
   - mvn install -Dmaven.javadoc.skip=true -B -V
script:
   - java -jar gateleen-playground/targer/libs/playground.jar &> playground_logs.log &
#   TODO: Instead of sleeping, should we rather make sure that the server Playground actually is running?
   - sleep 5s

#TODO - ./gradlew :gateleen-playground:uploadStaticFiles
   - mvn test -PuiIntegrationTests
   - kill $(ps -ef | grep playground | awk '{ print $2 }')
   - mvn test -PnonUiIntegrationTests
#TODO - ./gradlew jacocoTestReport


 #  - ./gradlew :gateleen-playground:uploadStaticFiles
 #  - ./gradlew :gateleen-test:test -PuiIntegrationTests -Dsel_chrome_driver=src/test/resources/chromedriver
 #  - kill $(ps -ef | grep playground | awk '{ print $2 }')
 #  - ./gradlew :gateleen-test:test -PnonUiIntegrationTests
 #  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)