language: java
dist: trusty
jdk:
  - oraclejdk11
services:
  - redis-server
before_install:
  - export DISPLAY=:99.0
  - chmod +x maybe-release.sh
  - sh -e /etc/init.d/xvfb start
#  Because newer versions of Chrome are not supported for the deprecated "precise" environment of travis we are using,
#  we download and install an older version of Chrome (v. 48), along with some dependencies.
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget http://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
  - sudo dpkg -i download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
#  We also download the newest version of Chrome Driver that still supports our old version of Chrome (v. 48).
  - wget https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d gateleen-test/src/test/resources/
# install groovy
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install groovy 3.0.8
install:
    - mvn install -Dmaven.javadoc.skip=true -PpublicRepos -B -V
before_script:
  - git config --global user.email "swisspush@post.ch"
  - git config --global user.name "Travis-CI"
script:
   - java -jar gateleen-playground/target/playground.jar &> playground_logs.log &
  # TODO: Instead of sleeping, should we rather make sure that the server Playground actually is running?
   - sleep 5s
   - mvn deploy -PuploadStaticFiles
   #- mvn install -PuiIntegrationTests
   - kill $(ps -ef | grep playground | awk '{ print $2 }')
   #- mvn install -PnonUiIntegrationTests
   # the exported credentials are needed in the maybe-release.sh
   - git config credential.helper "store --file=.git/credentials"
   - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
   - ./maybe-release.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
