language: java
# We use the deprecated travis environment "precise", because Gateleen does not yet support the newer redis version of the "trusty" environment.
dist: precise
jdk:
  - oraclejdk8
services:
  - redis-server
before_install:
  - export DISPLAY=:99.0
  - chmod +x maybe-release.sh
  - sh -e /etc/init.d/xvfb start
#  Because newer versions of Chrome are not supported for the deprecated "precise" environment of travis we are using,
#  we download and install an older version of Chrome (v. 48), along with some dependencies.
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget http://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
  - sudo dpkg -i download-chrome.php?file=lnx%2Fchrome64_48.0.2564.109.deb
#  We also download the newest version of Chrome Driver that still supports our old version of Chrome (v. 48).
  - wget https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d gateleen-test/src/test/resources/
install:
    # Normal build
    - mvn install -Dmaven.javadoc.skip=true -B -V

    # Release Build
#       - mvn -B -Prelease jgitflow:release-start jgitflow:release-finish --settings settings.xml
before_script:
  - git config --global user.email "swisspush@post.ch"
  - git config --global user.name "Travis-CI"
script:
   - java -jar gateleen-playground/target/playground.jar &> playground_logs.log &
##   TODO: Instead of sleeping, should we rather make sure that the server Playground actually is running?
   - sleep 5s
   - mvn deploy -PuploadStaticFiles
   - mvn install -PuiIntegrationTests
   - kill $(ps -ef | grep playground | awk '{ print $2 }')
   - mvn install -PnonUiIntegrationTests
   - git config credential.helper "store --file=.git/credentials"
   - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
   - ./maybe-release.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
